#############################################################################
# Makefile for building: qnapi
# Generated by qmake (2.01a) (Qt 4.3.2) on: niedz. mar 23 01:09:14 2008
# Project:  qnapi.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile qnapi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SHARED -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Itmp -Itmp
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmp/

####### Files

SOURCES       = src/main.cpp \
		src/napi.cpp \
		src/frmprogress.cpp \
		src/frmabout.cpp \
		src/frmoptions.cpp \
		src/frmupload.cpp \
		src/frmcorrect.cpp \
		src/frmreport.cpp \
		src/frmscan.cpp \
		src/frmcreateuser.cpp \
		src/qnapiconfig.cpp \
		src/qnapiapp.cpp \
		src/qdraglistwidget.cpp \
		src/movieinfo.cpp \
		src/multipartdata.cpp \
		src/qcumber/qinterprocesschannel.cpp \
		src/qcumber/qmanagedrequest.cpp \
		src/qcumber/qmanagedsocket.cpp \
		src/qcumber/qsingleapplication.cpp tmp/qrc_resources.cpp \
		tmp/moc_frmprogress.cpp \
		tmp/moc_frmabout.cpp \
		tmp/moc_frmoptions.cpp \
		tmp/moc_frmupload.cpp \
		tmp/moc_frmcorrect.cpp \
		tmp/moc_frmreport.cpp \
		tmp/moc_frmscan.cpp \
		tmp/moc_frmcreateuser.cpp \
		tmp/moc_qnapiapp.cpp \
		tmp/moc_qdraglistwidget.cpp \
		tmp/moc_napithread.cpp \
		tmp/moc_synchttp.cpp \
		tmp/moc_qinterprocesschannel.cpp \
		tmp/moc_qmanagedsocket.cpp \
		tmp/moc_qsingleapplication.cpp
OBJECTS       = tmp/main.o \
		tmp/napi.o \
		tmp/frmprogress.o \
		tmp/frmabout.o \
		tmp/frmoptions.o \
		tmp/frmupload.o \
		tmp/frmcorrect.o \
		tmp/frmreport.o \
		tmp/frmscan.o \
		tmp/frmcreateuser.o \
		tmp/qnapiconfig.o \
		tmp/qnapiapp.o \
		tmp/qdraglistwidget.o \
		tmp/movieinfo.o \
		tmp/multipartdata.o \
		tmp/qinterprocesschannel.o \
		tmp/qmanagedrequest.o \
		tmp/qmanagedsocket.o \
		tmp/qsingleapplication.o \
		tmp/qrc_resources.o \
		tmp/moc_frmprogress.o \
		tmp/moc_frmabout.o \
		tmp/moc_frmoptions.o \
		tmp/moc_frmupload.o \
		tmp/moc_frmcorrect.o \
		tmp/moc_frmreport.o \
		tmp/moc_frmscan.o \
		tmp/moc_frmcreateuser.o \
		tmp/moc_qnapiapp.o \
		tmp/moc_qdraglistwidget.o \
		tmp/moc_napithread.o \
		tmp/moc_synchttp.o \
		tmp/moc_qinterprocesschannel.o \
		tmp/moc_qmanagedsocket.o \
		tmp/moc_qsingleapplication.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		qnapi.pro
QMAKE_TARGET  = qnapi
DESTDIR       = 
TARGET        = qnapi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): tmp/ui_frmprogress.h tmp/ui_frmabout.h tmp/ui_frmoptions.h tmp/ui_frmupload.h tmp/ui_frmcorrect.h tmp/ui_frmreport.h tmp/ui_frmscan.h tmp/ui_frmcreateuser.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qnapi.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile qnapi.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qnapi.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/qnapi1.0.0 || $(MKDIR) tmp/qnapi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/qnapi1.0.0/ && $(COPY_FILE) --parents src/resources.qrc tmp/qnapi1.0.0/ && $(COPY_FILE) --parents src/napi.h src/frmprogress.h src/frmabout.h src/frmoptions.h src/frmupload.h src/frmcorrect.h src/frmreport.h src/frmscan.h src/frmcreateuser.h src/version.h src/qnapiconfig.h src/qnapiapp.h src/qdraglistwidget.h src/movieinfo.h src/multipartdata.h src/napithread.h src/synchttp.h src/qcumber/qinterprocesschannel.h src/qcumber/qmanagedrequest.h src/qcumber/qmanagedsocket.h src/qcumber/qsingleapplication.h src/qcumber/qcumber.h tmp/qnapi1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/napi.cpp src/frmprogress.cpp src/frmabout.cpp src/frmoptions.cpp src/frmupload.cpp src/frmcorrect.cpp src/frmreport.cpp src/frmscan.cpp src/frmcreateuser.cpp src/qnapiconfig.cpp src/qnapiapp.cpp src/qdraglistwidget.cpp src/movieinfo.cpp src/multipartdata.cpp src/qcumber/qinterprocesschannel.cpp src/qcumber/qmanagedrequest.cpp src/qcumber/qmanagedsocket.cpp src/qcumber/qsingleapplication.cpp tmp/qnapi1.0.0/ && $(COPY_FILE) --parents ui/frmprogress.ui ui/frmabout.ui ui/frmoptions.ui ui/frmupload.ui ui/frmcorrect.ui ui/frmreport.ui ui/frmscan.ui ui/frmcreateuser.ui tmp/qnapi1.0.0/ && (cd `dirname tmp/qnapi1.0.0` && $(TAR) qnapi1.0.0.tar qnapi1.0.0 && $(COMPRESS) qnapi1.0.0.tar) && $(MOVE) `dirname tmp/qnapi1.0.0`/qnapi1.0.0.tar.gz . && $(DEL_FILE) -r tmp/qnapi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_rcc_make_all: tmp/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) tmp/qrc_resources.cpp
tmp/qrc_resources.cpp: src/resources.qrc \
		src/qnapi-22-mono.png \
		src/qnapi.png \
		src/qnapi-48.png \
		src/qnapi-48-icon.png
	/usr/bin/rcc -name resources src/resources.qrc -o tmp/qrc_resources.cpp

compiler_moc_header_make_all: tmp/moc_frmprogress.cpp tmp/moc_frmabout.cpp tmp/moc_frmoptions.cpp tmp/moc_frmupload.cpp tmp/moc_frmcorrect.cpp tmp/moc_frmreport.cpp tmp/moc_frmscan.cpp tmp/moc_frmcreateuser.cpp tmp/moc_qnapiapp.cpp tmp/moc_qdraglistwidget.cpp tmp/moc_napithread.cpp tmp/moc_synchttp.cpp tmp/moc_qinterprocesschannel.cpp tmp/moc_qmanagedsocket.cpp tmp/moc_qsingleapplication.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc_frmprogress.cpp tmp/moc_frmabout.cpp tmp/moc_frmoptions.cpp tmp/moc_frmupload.cpp tmp/moc_frmcorrect.cpp tmp/moc_frmreport.cpp tmp/moc_frmscan.cpp tmp/moc_frmcreateuser.cpp tmp/moc_qnapiapp.cpp tmp/moc_qdraglistwidget.cpp tmp/moc_napithread.cpp tmp/moc_synchttp.cpp tmp/moc_qinterprocesschannel.cpp tmp/moc_qmanagedsocket.cpp tmp/moc_qsingleapplication.cpp
tmp/moc_frmprogress.cpp: tmp/ui_frmprogress.h \
		src/frmabout.h \
		tmp/ui_frmabout.h \
		src/version.h \
		src/qnapiconfig.h \
		src/frmoptions.h \
		tmp/ui_frmoptions.h \
		src/frmcreateuser.h \
		tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmupload.h \
		tmp/ui_frmupload.h \
		src/frmcorrect.h \
		tmp/ui_frmcorrect.h \
		src/frmreport.h \
		tmp/ui_frmreport.h \
		src/frmscan.h \
		tmp/ui_frmscan.h \
		src/qdraglistwidget.h \
		src/frmprogress.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmprogress.h -o tmp/moc_frmprogress.cpp

tmp/moc_frmabout.cpp: tmp/ui_frmabout.h \
		src/version.h \
		src/qnapiconfig.h \
		src/frmabout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmabout.h -o tmp/moc_frmabout.cpp

tmp/moc_frmoptions.cpp: tmp/ui_frmoptions.h \
		src/qnapiconfig.h \
		src/version.h \
		src/frmcreateuser.h \
		tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmoptions.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmoptions.h -o tmp/moc_frmoptions.cpp

tmp/moc_frmupload.cpp: tmp/ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h \
		src/frmupload.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmupload.h -o tmp/moc_frmupload.cpp

tmp/moc_frmcorrect.cpp: tmp/ui_frmcorrect.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h \
		src/frmcorrect.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmcorrect.h -o tmp/moc_frmcorrect.cpp

tmp/moc_frmreport.cpp: tmp/ui_frmreport.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h \
		src/frmreport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmreport.h -o tmp/moc_frmreport.cpp

tmp/moc_frmscan.cpp: tmp/ui_frmscan.h \
		src/qdraglistwidget.h \
		src/napithread.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/frmscan.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmscan.h -o tmp/moc_frmscan.cpp

tmp/moc_frmcreateuser.cpp: tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h \
		src/frmcreateuser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmcreateuser.h -o tmp/moc_frmcreateuser.cpp

tmp/moc_qnapiapp.cpp: src/qcumber/qsingleapplication.h \
		src/qcumber/qcumber.h \
		src/qnapiapp.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qnapiapp.h -o tmp/moc_qnapiapp.cpp

tmp/moc_qdraglistwidget.cpp: src/qdraglistwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qdraglistwidget.h -o tmp/moc_qdraglistwidget.cpp

tmp/moc_napithread.cpp: src/napithread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/napithread.h -o tmp/moc_napithread.cpp

tmp/moc_synchttp.cpp: src/synchttp.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/synchttp.h -o tmp/moc_synchttp.cpp

tmp/moc_qinterprocesschannel.cpp: src/qcumber/qcumber.h \
		src/qcumber/qinterprocesschannel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qcumber/qinterprocesschannel.h -o tmp/moc_qinterprocesschannel.cpp

tmp/moc_qmanagedsocket.cpp: src/qcumber/qcumber.h \
		src/qcumber/qmanagedsocket.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qcumber/qmanagedsocket.h -o tmp/moc_qmanagedsocket.cpp

tmp/moc_qsingleapplication.cpp: src/qcumber/qcumber.h \
		src/qcumber/qsingleapplication.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qcumber/qsingleapplication.h -o tmp/moc_qsingleapplication.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: tmp/ui_frmprogress.h tmp/ui_frmabout.h tmp/ui_frmoptions.h tmp/ui_frmupload.h tmp/ui_frmcorrect.h tmp/ui_frmreport.h tmp/ui_frmscan.h tmp/ui_frmcreateuser.h
compiler_uic_clean:
	-$(DEL_FILE) tmp/ui_frmprogress.h tmp/ui_frmabout.h tmp/ui_frmoptions.h tmp/ui_frmupload.h tmp/ui_frmcorrect.h tmp/ui_frmreport.h tmp/ui_frmscan.h tmp/ui_frmcreateuser.h
tmp/ui_frmprogress.h: ui/frmprogress.ui
	/usr/bin/uic-qt4 ui/frmprogress.ui -o tmp/ui_frmprogress.h

tmp/ui_frmabout.h: ui/frmabout.ui
	/usr/bin/uic-qt4 ui/frmabout.ui -o tmp/ui_frmabout.h

tmp/ui_frmoptions.h: ui/frmoptions.ui
	/usr/bin/uic-qt4 ui/frmoptions.ui -o tmp/ui_frmoptions.h

tmp/ui_frmupload.h: ui/frmupload.ui
	/usr/bin/uic-qt4 ui/frmupload.ui -o tmp/ui_frmupload.h

tmp/ui_frmcorrect.h: ui/frmcorrect.ui
	/usr/bin/uic-qt4 ui/frmcorrect.ui -o tmp/ui_frmcorrect.h

tmp/ui_frmreport.h: ui/frmreport.ui
	/usr/bin/uic-qt4 ui/frmreport.ui -o tmp/ui_frmreport.h

tmp/ui_frmscan.h: ui/frmscan.ui \
		src/qdraglistwidget.h
	/usr/bin/uic-qt4 ui/frmscan.ui -o tmp/ui_frmscan.h

tmp/ui_frmcreateuser.h: ui/frmcreateuser.ui
	/usr/bin/uic-qt4 ui/frmcreateuser.ui -o tmp/ui_frmcreateuser.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

tmp/main.o: src/main.cpp src/frmprogress.h \
		tmp/ui_frmprogress.h \
		src/frmabout.h \
		tmp/ui_frmabout.h \
		src/version.h \
		src/qnapiconfig.h \
		src/frmoptions.h \
		tmp/ui_frmoptions.h \
		src/frmcreateuser.h \
		tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmupload.h \
		tmp/ui_frmupload.h \
		src/frmcorrect.h \
		tmp/ui_frmcorrect.h \
		src/frmreport.h \
		tmp/ui_frmreport.h \
		src/frmscan.h \
		tmp/ui_frmscan.h \
		src/qdraglistwidget.h \
		src/qnapiapp.h \
		src/qcumber/qsingleapplication.h \
		src/qcumber/qcumber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/main.o src/main.cpp

tmp/napi.o: src/napi.cpp src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/napi.o src/napi.cpp

tmp/frmprogress.o: src/frmprogress.cpp src/frmprogress.h \
		tmp/ui_frmprogress.h \
		src/frmabout.h \
		tmp/ui_frmabout.h \
		src/version.h \
		src/qnapiconfig.h \
		src/frmoptions.h \
		tmp/ui_frmoptions.h \
		src/frmcreateuser.h \
		tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmupload.h \
		tmp/ui_frmupload.h \
		src/frmcorrect.h \
		tmp/ui_frmcorrect.h \
		src/frmreport.h \
		tmp/ui_frmreport.h \
		src/frmscan.h \
		tmp/ui_frmscan.h \
		src/qdraglistwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmprogress.o src/frmprogress.cpp

tmp/frmabout.o: src/frmabout.cpp src/frmabout.h \
		tmp/ui_frmabout.h \
		src/version.h \
		src/qnapiconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmabout.o src/frmabout.cpp

tmp/frmoptions.o: src/frmoptions.cpp src/frmoptions.h \
		tmp/ui_frmoptions.h \
		src/qnapiconfig.h \
		src/version.h \
		src/frmcreateuser.h \
		tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmoptions.o src/frmoptions.cpp

tmp/frmupload.o: src/frmupload.cpp src/frmupload.h \
		tmp/ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmupload.o src/frmupload.cpp

tmp/frmcorrect.o: src/frmcorrect.cpp src/frmcorrect.h \
		tmp/ui_frmcorrect.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmcorrect.o src/frmcorrect.cpp

tmp/frmreport.o: src/frmreport.cpp src/frmreport.h \
		tmp/ui_frmreport.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmreport.o src/frmreport.cpp

tmp/frmscan.o: src/frmscan.cpp src/frmscan.h \
		tmp/ui_frmscan.h \
		src/qdraglistwidget.h \
		src/napithread.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmscan.o src/frmscan.cpp

tmp/frmcreateuser.o: src/frmcreateuser.cpp src/frmcreateuser.h \
		tmp/ui_frmcreateuser.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/version.h \
		src/qnapiconfig.h \
		src/napithread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/frmcreateuser.o src/frmcreateuser.cpp

tmp/qnapiconfig.o: src/qnapiconfig.cpp src/qnapiconfig.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qnapiconfig.o src/qnapiconfig.cpp

tmp/qnapiapp.o: src/qnapiapp.cpp src/qnapiapp.h \
		src/qcumber/qsingleapplication.h \
		src/qcumber/qcumber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qnapiapp.o src/qnapiapp.cpp

tmp/qdraglistwidget.o: src/qdraglistwidget.cpp src/qdraglistwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qdraglistwidget.o src/qdraglistwidget.cpp

tmp/movieinfo.o: src/movieinfo.cpp src/movieinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/movieinfo.o src/movieinfo.cpp

tmp/multipartdata.o: src/multipartdata.cpp src/multipartdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/multipartdata.o src/multipartdata.cpp

tmp/qinterprocesschannel.o: src/qcumber/qinterprocesschannel.cpp src/qcumber/qinterprocesschannel.h \
		src/qcumber/qcumber.h \
		src/qcumber/qmanagedsocket.h \
		src/qcumber/qmanagedrequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qinterprocesschannel.o src/qcumber/qinterprocesschannel.cpp

tmp/qmanagedrequest.o: src/qcumber/qmanagedrequest.cpp src/qcumber/qmanagedrequest.h \
		src/qcumber/qcumber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qmanagedrequest.o src/qcumber/qmanagedrequest.cpp

tmp/qmanagedsocket.o: src/qcumber/qmanagedsocket.cpp src/qcumber/qmanagedsocket.h \
		src/qcumber/qcumber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qmanagedsocket.o src/qcumber/qmanagedsocket.cpp

tmp/qsingleapplication.o: src/qcumber/qsingleapplication.cpp src/qcumber/qsingleapplication.h \
		src/qcumber/qcumber.h \
		src/qcumber/qmanagedrequest.h \
		src/qcumber/qinterprocesschannel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qsingleapplication.o src/qcumber/qsingleapplication.cpp

tmp/qrc_resources.o: tmp/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qrc_resources.o tmp/qrc_resources.cpp

tmp/moc_frmprogress.o: tmp/moc_frmprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmprogress.o tmp/moc_frmprogress.cpp

tmp/moc_frmabout.o: tmp/moc_frmabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmabout.o tmp/moc_frmabout.cpp

tmp/moc_frmoptions.o: tmp/moc_frmoptions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmoptions.o tmp/moc_frmoptions.cpp

tmp/moc_frmupload.o: tmp/moc_frmupload.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmupload.o tmp/moc_frmupload.cpp

tmp/moc_frmcorrect.o: tmp/moc_frmcorrect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmcorrect.o tmp/moc_frmcorrect.cpp

tmp/moc_frmreport.o: tmp/moc_frmreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmreport.o tmp/moc_frmreport.cpp

tmp/moc_frmscan.o: tmp/moc_frmscan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmscan.o tmp/moc_frmscan.cpp

tmp/moc_frmcreateuser.o: tmp/moc_frmcreateuser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_frmcreateuser.o tmp/moc_frmcreateuser.cpp

tmp/moc_qnapiapp.o: tmp/moc_qnapiapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_qnapiapp.o tmp/moc_qnapiapp.cpp

tmp/moc_qdraglistwidget.o: tmp/moc_qdraglistwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_qdraglistwidget.o tmp/moc_qdraglistwidget.cpp

tmp/moc_napithread.o: tmp/moc_napithread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_napithread.o tmp/moc_napithread.cpp

tmp/moc_synchttp.o: tmp/moc_synchttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_synchttp.o tmp/moc_synchttp.cpp

tmp/moc_qinterprocesschannel.o: tmp/moc_qinterprocesschannel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_qinterprocesschannel.o tmp/moc_qinterprocesschannel.cpp

tmp/moc_qmanagedsocket.o: tmp/moc_qmanagedsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_qmanagedsocket.o tmp/moc_qmanagedsocket.cpp

tmp/moc_qsingleapplication.o: tmp/moc_qsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_qsingleapplication.o tmp/moc_qsingleapplication.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

