#############################################################################
# Makefile for building: qnapi
# Generated by qmake (2.01a) (Qt 4.3.2) on: pon. lut 18 08:23:28 2008
# Project:  qnapi.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile qnapi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SHARED -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/napi.cpp \
		src/frmprogress.cpp \
		src/frmabout.cpp \
		src/frmoptions.cpp \
		src/multipartdata.cpp \
		src/movieinfo.cpp \
		src/frmupload.cpp \
		src/frmcorrect.cpp \
		src/frmreport.cpp \
		src/qnapiconfig.cpp qrc_resources.cpp \
		moc_frmprogress.cpp \
		moc_synchttp.cpp \
		moc_frmabout.cpp \
		moc_frmoptions.cpp \
		moc_frmupload.cpp \
		moc_napithread.cpp \
		moc_frmcorrect.cpp \
		moc_frmreport.cpp
OBJECTS       = main.o \
		napi.o \
		frmprogress.o \
		frmabout.o \
		frmoptions.o \
		multipartdata.o \
		movieinfo.o \
		frmupload.o \
		frmcorrect.o \
		frmreport.o \
		qnapiconfig.o \
		qrc_resources.o \
		moc_frmprogress.o \
		moc_synchttp.o \
		moc_frmabout.o \
		moc_frmoptions.o \
		moc_frmupload.o \
		moc_napithread.o \
		moc_frmcorrect.o \
		moc_frmreport.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		qnapi.pro
QMAKE_TARGET  = qnapi
DESTDIR       = 
TARGET        = qnapi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_frmprogress.h ui_frmabout.h ui_frmoptions.h ui_frmupload.h ui_frmcorrect.h ui_frmreport.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qnapi.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile qnapi.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qnapi.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qnapi1.0.0 || $(MKDIR) .tmp/qnapi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qnapi1.0.0/ && $(COPY_FILE) --parents src/resources.qrc .tmp/qnapi1.0.0/ && $(COPY_FILE) --parents src/napi.h src/frmprogress.h src/synchttp.h src/frmabout.h src/frmoptions.h src/multipartdata.h src/movieinfo.h src/frmupload.h src/napithread.h src/frmcorrect.h src/frmreport.h src/version.h src/qnapiconfig.h .tmp/qnapi1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/napi.cpp src/frmprogress.cpp src/frmabout.cpp src/frmoptions.cpp src/multipartdata.cpp src/movieinfo.cpp src/frmupload.cpp src/frmcorrect.cpp src/frmreport.cpp src/qnapiconfig.cpp .tmp/qnapi1.0.0/ && $(COPY_FILE) --parents ui/frmprogress.ui ui/frmabout.ui ui/frmoptions.ui ui/frmupload.ui ui/frmcorrect.ui ui/frmreport.ui .tmp/qnapi1.0.0/ && (cd `dirname .tmp/qnapi1.0.0` && $(TAR) qnapi1.0.0.tar qnapi1.0.0 && $(COMPRESS) qnapi1.0.0.tar) && $(MOVE) `dirname .tmp/qnapi1.0.0`/qnapi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qnapi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: src/resources.qrc \
		src/qnapi.png \
		src/qnapi_mono.png \
		src/qnapi_44x44.png
	/usr/bin/rcc -name resources src/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_frmprogress.cpp moc_synchttp.cpp moc_frmabout.cpp moc_frmoptions.cpp moc_frmupload.cpp moc_napithread.cpp moc_frmcorrect.cpp moc_frmreport.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_frmprogress.cpp moc_synchttp.cpp moc_frmabout.cpp moc_frmoptions.cpp moc_frmupload.cpp moc_napithread.cpp moc_frmcorrect.cpp moc_frmreport.cpp
moc_frmprogress.cpp: ui_frmprogress.h \
		src/frmabout.h \
		ui_frmabout.h \
		src/version.h \
		src/frmoptions.h \
		ui_frmoptions.h \
		src/qnapiconfig.h \
		src/frmupload.h \
		ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmcorrect.h \
		ui_frmcorrect.h \
		src/frmreport.h \
		ui_frmreport.h \
		src/frmprogress.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmprogress.h -o moc_frmprogress.cpp

moc_synchttp.cpp: src/synchttp.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/synchttp.h -o moc_synchttp.cpp

moc_frmabout.cpp: ui_frmabout.h \
		src/version.h \
		src/frmabout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmabout.h -o moc_frmabout.cpp

moc_frmoptions.cpp: ui_frmoptions.h \
		src/qnapiconfig.h \
		src/version.h \
		src/frmoptions.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmoptions.h -o moc_frmoptions.cpp

moc_frmupload.cpp: ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/qnapiconfig.h \
		src/version.h \
		src/frmupload.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmupload.h -o moc_frmupload.cpp

moc_napithread.cpp: src/napithread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/napithread.h -o moc_napithread.cpp

moc_frmcorrect.cpp: ui_frmcorrect.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/qnapiconfig.h \
		src/version.h \
		src/frmcorrect.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmcorrect.h -o moc_frmcorrect.cpp

moc_frmreport.cpp: ui_frmreport.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/qnapiconfig.h \
		src/version.h \
		src/frmreport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/frmreport.h -o moc_frmreport.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_frmprogress.h ui_frmabout.h ui_frmoptions.h ui_frmupload.h ui_frmcorrect.h ui_frmreport.h
compiler_uic_clean:
	-$(DEL_FILE) ui_frmprogress.h ui_frmabout.h ui_frmoptions.h ui_frmupload.h ui_frmcorrect.h ui_frmreport.h
ui_frmprogress.h: ui/frmprogress.ui
	/usr/bin/uic-qt4 ui/frmprogress.ui -o ui_frmprogress.h

ui_frmabout.h: ui/frmabout.ui
	/usr/bin/uic-qt4 ui/frmabout.ui -o ui_frmabout.h

ui_frmoptions.h: ui/frmoptions.ui
	/usr/bin/uic-qt4 ui/frmoptions.ui -o ui_frmoptions.h

ui_frmupload.h: ui/frmupload.ui
	/usr/bin/uic-qt4 ui/frmupload.ui -o ui_frmupload.h

ui_frmcorrect.h: ui/frmcorrect.ui
	/usr/bin/uic-qt4 ui/frmcorrect.ui -o ui_frmcorrect.h

ui_frmreport.h: ui/frmreport.ui
	/usr/bin/uic-qt4 ui/frmreport.ui -o ui_frmreport.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/frmprogress.h \
		ui_frmprogress.h \
		src/frmabout.h \
		ui_frmabout.h \
		src/version.h \
		src/frmoptions.h \
		ui_frmoptions.h \
		src/qnapiconfig.h \
		src/frmupload.h \
		ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmcorrect.h \
		ui_frmcorrect.h \
		src/frmreport.h \
		ui_frmreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

napi.o: src/napi.cpp src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o napi.o src/napi.cpp

frmprogress.o: src/frmprogress.cpp src/frmprogress.h \
		ui_frmprogress.h \
		src/frmabout.h \
		ui_frmabout.h \
		src/version.h \
		src/frmoptions.h \
		ui_frmoptions.h \
		src/qnapiconfig.h \
		src/frmupload.h \
		ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/frmcorrect.h \
		ui_frmcorrect.h \
		src/frmreport.h \
		ui_frmreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmprogress.o src/frmprogress.cpp

frmabout.o: src/frmabout.cpp src/frmabout.h \
		ui_frmabout.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmabout.o src/frmabout.cpp

frmoptions.o: src/frmoptions.cpp src/frmoptions.h \
		ui_frmoptions.h \
		src/qnapiconfig.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmoptions.o src/frmoptions.cpp

multipartdata.o: src/multipartdata.cpp src/multipartdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multipartdata.o src/multipartdata.cpp

movieinfo.o: src/movieinfo.cpp src/movieinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movieinfo.o src/movieinfo.cpp

frmupload.o: src/frmupload.cpp src/frmupload.h \
		ui_frmupload.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/qnapiconfig.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmupload.o src/frmupload.cpp

frmcorrect.o: src/frmcorrect.cpp src/frmcorrect.h \
		ui_frmcorrect.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/qnapiconfig.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmcorrect.o src/frmcorrect.cpp

frmreport.o: src/frmreport.cpp src/frmreport.h \
		ui_frmreport.h \
		src/napi.h \
		src/synchttp.h \
		src/multipartdata.h \
		src/movieinfo.h \
		src/napithread.h \
		src/qnapiconfig.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmreport.o src/frmreport.cpp

qnapiconfig.o: src/qnapiconfig.cpp src/qnapiconfig.h \
		src/version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qnapiconfig.o src/qnapiconfig.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_frmprogress.o: moc_frmprogress.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmprogress.o moc_frmprogress.cpp

moc_synchttp.o: moc_synchttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_synchttp.o moc_synchttp.cpp

moc_frmabout.o: moc_frmabout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmabout.o moc_frmabout.cpp

moc_frmoptions.o: moc_frmoptions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmoptions.o moc_frmoptions.cpp

moc_frmupload.o: moc_frmupload.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmupload.o moc_frmupload.cpp

moc_napithread.o: moc_napithread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_napithread.o moc_napithread.cpp

moc_frmcorrect.o: moc_frmcorrect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmcorrect.o moc_frmcorrect.cpp

moc_frmreport.o: moc_frmreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmreport.o moc_frmreport.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

