.TH "qnapi" 1
.SH NAZWA
qnapi \- program do pobierania napisow z bazy NAPI-PROJEKT.
.SH SKLADNIA
\fBqnapi\fP [opcje] [lista plikow]
.SH OPIS
\fBqnapi\fP potrafi pracowac w dwoch trybach: GUI oraz konsolowym. Podanie listy plikow (filmowych) zmusi program do pobrania napisow dla zadanych filmow.
.SH OPCJE
    -c, \-\-console    pobieranie napisow z konsoli
    -q, \-\-quiet      pobiera napisy nie wypisujac zadnych komunikatow
                     ani nie pokazujac zadnych okien
    -h, \-\-help       pokazuje pomoc programu
.SH AUTOR
Copyright (C) 2008 Krzemin <pkrzemin@o2.pl>
.SH LICENCJA
Program QNapi rozprowadzany jest na licencji GNU General Public License w wersji 2. lub kazdej pozniejszej.
.SH BLEDY
Wszelkie zauwazone bledy w programie mozna zglaszac w trackerze na sourceforge.net: http://sourceforge.net/projects/qnapi
